spring.application.name=smartLaundry

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# JWT
 jwt.secret=SmartLaundrySecretKeyForJwtAuthentication2026SmartLaundrySystem
 jwt.expiration=86400000

springdoc.openapi.servers[0].url=https://slapi-production-112f.up.railway.app
springdoc.openapi.servers[0].description=Production Server
